ES-96/SBOM generation
corda/corda-cli-plugin-host pull request #172
Opened 2023-06-19 14:51 UTC by seanbrereton

Creating SBOM using the cyclonedx plugin.
Adding a task to zip the sboms into 1 folder and publish them.
Tested locally: https://gradle.dev.r3.com/s/fhdql7ghlvoy4

2023-06-19 16:20 UTC, yarivus submitted a review, later dismissed
LGTM

2023-06-20 08:58 UTC, ronanbrowne requested changes
See

2023-06-20 08:58 UTC, ronanbrowne commented on settings.gradle
> +        id "org.cyclonedx.bom" version "1.7.4"
Can we externalize the hard-coded version to gradle.propertiers please

2023-06-20 12:22 UTC, ronanbrowne approved these changes
LGTM

2023-06-20 12:23 UTC, yarivus approved these changes
LGTM

2023-06-20 12:44 UTC, merged